server:
  http2:
    enabled: true
  error:
    include-message: always
    include-binding-errors: always

card-checking:
  security:
    jwt:
      secret: GnBGcKJvQJ93KCVVxXxkYL7RNWqYACCaMT9pNXmx7R949KKnrFsad3GVD3VkK3Qw
      expireIn: 1500000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bankapp_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 3523
  jpa:
    open-in-view: false
    show-sql: true
